import TopcatsSide from '@/components/contents/cats/slide/TopcatsSide';
import Header from '@/components/contents/header/Header';
import Layout from '@/components/layout/Layout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>kittneQueen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="">
        <div>
          <Layout>
            <div>
              <Header />
            </div>

            <div className="bg-slate-100 pt-10">
              <div className="my-20">
                <article>
                  <h1 className="text-4xl text-slate-700  text-center">
                    Top 10 Cats
                  </h1>
                </article>
              </div>
              <TopcatsSide />
            </div>

            <div></div>
          </Layout>
        </div>
      </main>
    </>
  );
}
