import Header from '@/components/contents/header/Header';
import Layout from '@/components/layout/Layout';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>kittneQueen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/logo_cat.png" />
      </Head>
      <main className="">
        <div>
          <Layout>
            <div>
              <Header />
            </div>
          </Layout>
        </div>
      </main>
    </>
  );
}
